"""initial migration

Revision ID: 0ae22326060d
Revises: 
Create Date: 2024-06-14 22:24:06.052045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ae22326060d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('front_picture', sa.String(), nullable=True),
    sa.Column('back_picture', sa.String(), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('special_attack', sa.Integer(), nullable=False),
    sa.Column('special_defense', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pokemons')),
    sa.UniqueConstraint('id', name=op.f('uq_pokemons_id'))
    )
    op.create_table('types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_types')),
    sa.UniqueConstraint('id', name=op.f('uq_types_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('types')
    op.drop_table('pokemons')
    # ### end Alembic commands ###
