"""Populate tables

Revision ID: 1e846fcc471e
Revises: 0ae22326060d
Create Date: 2024-06-14 22:25:52.106822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e846fcc471e'
down_revision: Union[str, None] = '0ae22326060d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_pokemons_id'), 'pokemons', ['id'])
    op.create_unique_constraint(op.f('uq_types_id'), 'types', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_types_id'), 'types', type_='unique')
    op.drop_constraint(op.f('uq_pokemons_id'), 'pokemons', type_='unique')
    # ### end Alembic commands ###
